services:
  nginx:
    image: nginx:1.28.0-alpine
    container_name: nginx-L12
    volumes:
      - ./php:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    ports:
      - "4001:80"
    depends_on:
      - php-fpm
    networks:
      - backend
      - frontend

  php-fpm:
      image: php:8.3-fpm-alpine3.20
      container_name: php-fpm-L12
      volumes:
        - ./php:/var/www/html:ro
      restart: unless-stopped
      depends_on:
        - mysql
      networks:
        - backend

  mysql:
    image: mysql:9.3
    container_name: mysql-L12
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: bazatestowa
      MYSQL_USER: testuser
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    secrets:
      - mysql_user_password
      - mysql_root_password
    networks:
      - backend
  
  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin-L12
    restart: unless-stopped
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    depends_on:
        - mysql
    networks:
      - backend

volumes:
  mysql-data:

secrets:
  mysql_user_password:
    file: ./mysql_user_password.txt
  mysql_root_password:
    file: ./mysql_root_password.txt

networks:
  backend:
  frontend: